#!/bin/bash
#run pretraining script

    horovodrun -np 16 -H localhost:8,172.31.59.241:8 \
      python run_pretraining.py \
	    --data-dir /home/ubuntu/electra_data/ \
	    --model-name electra_small_owt \
	    --hparams '{"train_batch_size":128}'